### ISSUE TITLE
Error in Work Item example

### ISSUE THREAD

**Issue by ben-miller** [bunkat/schedule#16]
It appears that 'schedule' is no longer a function.  

```
$ node test.js
.../test.js:94
          .schedule(function(d) { return d.availability ? p(d.availability) : undefined; })
           ^

TypeError: schedule.tasks(...).id(...).duration(...).schedule is not a function
    at Object.<anonymous> (/Users/bmiller/src/clockwork.js/test.js:94:12)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3
```

**Comment by yellic** [comment]
change schedule to available
the function name has changed in source code , but the example are not updated accordingly
